import "dotenv/config";
import { PrismaClient, Role, Status, TaskStatus, Priority, ActivityType, IssueStatus } from "@prisma/client";
import bcrypt from "bcryptjs";
const prisma = new PrismaClient();
const at=(day:number,hour=12,minute=0)=>new Date(Date.UTC(2026,6,day,hour,minute));
async function main(){
  const passwordHash=await bcrypt.hash("ChangeMe123!",12);
  const admin=await prisma.user.upsert({where:{email:"admin@farmpulse.local"},update:{name:"Wilkes Ladera",passwordHash,role:Role.ADMIN},create:{email:"admin@farmpulse.local",name:"Wilkes Ladera",passwordHash,role:Role.ADMIN}});
  const operator=await prisma.user.upsert({where:{email:"operator@farmpulse.local"},update:{passwordHash,role:Role.OPERATOR},create:{email:"operator@farmpulse.local",name:"Mateo Rivera",passwordHash,role:Role.OPERATOR}});
  let farm=await prisma.farm.findFirst({where:{name:"FarmPulse Panama Pilot"}});
  if(!farm)farm=await prisma.farm.create({data:{name:"FarmPulse Panama Pilot",country:"Panama",timezone:"America/Panama",currency:"USD",unitSystem:"METRIC",latitude:8.43,longitude:-82.43}});
  for(const [user,role] of [[admin,Role.ADMIN],[operator,Role.OPERATOR]] as const)await prisma.farmMembership.upsert({where:{farmId_userId:{farmId:farm.id,userId:user.id}},update:{role},create:{farmId:farm.id,userId:user.id,role}});
  let field=await prisma.field.findFirst({where:{farmId:farm.id,name:"Field 1"}});
  if(!field)field=await prisma.field.create({data:{farmId:farm.id,name:"Field 1",areaHa:1,status:Status.ACTIVE}});
  const sectors=[];for(let i=1;i<=4;i++){const sector=await prisma.sector.upsert({where:{fieldId_name:{fieldId:field.id,name:`Sector ${i}`}},update:{dripLines:i===3?34:33},create:{fieldId:field.id,name:`Sector ${i}`,dripLines:i===3?34:33,status:i===2?"Irrigation due":i===3?"Attention needed":"Healthy"}});sectors.push(sector)}
  const crop=await prisma.crop.upsert({where:{name:"Corn"},update:{},create:{name:"Corn",scientificName:"Zea mays"}});
  const stageNames=["Planning","Land preparation","Planting","Germination","Seedling","Vegetative growth","Tasseling","Silking","Grain filling","Maturity","Harvest","Completed"];
  const stages=[];for(const [order,name] of stageNames.entries())stages.push(await prisma.growthStage.upsert({where:{cropId_name:{cropId:crop.id,name}},update:{order},create:{cropId:crop.id,name,order}}));
  let cycle=await prisma.cropCycle.findFirst({where:{fieldId:field.id,status:Status.ACTIVE}});
  if(!cycle)cycle=await prisma.cropCycle.create({data:{fieldId:field.id,cropId:crop.id,growthStageId:stages[4].id,variety:"Pioneer P4226",plannedPlantingDate:at(18),actualPlantingDate:at(18),expectedHarvestDate:new Date(Date.UTC(2026,10,12)),seedQuantityKg:22,populationTarget:60000,expectedYieldKg:7500,status:Status.ACTIVE,notes:"Sample pilot crop cycle."}});
  for(const sector of sectors)await prisma.cropCycleSector.upsert({where:{cropCycleId_sectorId:{cropCycleId:cycle.id,sectorId:sector.id}},update:{},create:{cropCycleId:cycle.id,sectorId:sector.id}});
  if(await prisma.task.count({where:{fieldId:field.id}})===0)await prisma.task.createMany({data:[{fieldId:field.id,sectorId:sectors[1].id,cropCycleId:cycle.id,assignedUserId:operator.id,name:"Irrigate Sector 2",category:"Irrigation",priority:Priority.HIGH,dueAt:at(31,12),status:TaskStatus.DUE_TODAY},{fieldId:field.id,sectorId:sectors[2].id,cropCycleId:cycle.id,assignedUserId:operator.id,name:"Inspect reported drip-line leak",category:"Maintenance",priority:Priority.CRITICAL,dueAt:at(30,14),status:TaskStatus.OVERDUE},{fieldId:field.id,cropCycleId:cycle.id,assignedUserId:operator.id,name:"Scout seedling emergence",category:"Pest inspection",priority:Priority.MEDIUM,dueAt:at(31,20),status:TaskStatus.DUE_TODAY}]});
  if(await prisma.activity.count({where:{fieldId:field.id}})===0){const activity=await prisma.activity.create({data:{fieldId:field.id,sectorId:sectors[0].id,cropCycleId:cycle.id,createdById:operator.id,type:ActivityType.IRRIGATION,occurredAt:at(31,11,20),startTime:at(31,10,20),endTime:at(31,11,22),quantity:11367,unit:"liter",worker:operator.name,notes:"Sample irrigation record."}});await prisma.irrigationEvent.create({data:{sectorId:sectors[0].id,activityId:activity.id,startedAt:at(31,10,20),durationMinutes:62,flowM3h:11,estimatedLiters:11367,pressureBar:1.2,pumpRuntimeMinutes:62,operator:operator.name}});}
  if(await prisma.expense.count({where:{fieldId:field.id}})===0)await prisma.expense.createMany({data:[{fieldId:field.id,cropCycleId:cycle.id,enteredById:admin.id,date:at(12),vendor:"Semillas del Istmo",description:"Corn seed",category:"Seed",amount:640},{fieldId:field.id,cropCycleId:cycle.id,enteredById:admin.id,date:at(24),vendor:"Local crew",description:"Field labor",category:"Labor",amount:280},{fieldId:field.id,cropCycleId:cycle.id,enteredById:admin.id,date:at(28),vendor:"Agro Panamá",description:"Nitrogen fertilizer",category:"Fertilizer",amount:420}]});
  if(await prisma.budget.count({where:{farmId:farm.id}})===0)await prisma.budget.create({data:{farmId:farm.id,cropCycleId:cycle.id,name:"2026 corn pilot budget",plannedAmount:8500}});
  if(await prisma.inventoryItem.count({where:{farmId:farm.id}})===0)await prisma.inventoryItem.createMany({data:[{farmId:farm.id,name:"Corn seed · Pioneer P4226",category:"Seeds",quantityOnHand:18,unit:"kg",minimumThreshold:10,unitCost:29,storageLocation:"Seed storage"},{farmId:farm.id,name:"Nitrogen fertilizer",category:"Fertilizer",quantityOnHand:22,unit:"kg",minimumThreshold:30,unitCost:1.8,storageLocation:"Input shed"},{farmId:farm.id,name:"16 mm drip tape",category:"Drip tape",quantityOnHand:1,unit:"roll",minimumThreshold:2,unitCost:120,storageLocation:"Pump shed"}]});
  if(await prisma.equipment.count({where:{farmId:farm.id}})===0)await prisma.equipment.createMany({data:[{farmId:farm.id,name:"River intake pump",type:"Pump",status:"Operational",runtimeHours:18.2},{farmId:farm.id,name:"Irrigation pressure pump",type:"Pump",status:"Operational",runtimeHours:24.3,nextMaintenance:at(6)},{farmId:farm.id,name:"24,000 L storage tank",type:"Storage tank",status:"Operational"},{farmId:farm.id,name:"Main irrigation filter",type:"Filter",status:"Operational",lastMaintenance:at(30)}]});
  if(await prisma.fieldNote.count({where:{fieldId:field.id}})===0)await prisma.fieldNote.create({data:{fieldId:field.id,sectorId:sectors[3].id,createdById:operator.id,category:"Field observation",body:"Sample record: emergence looks even; photograph a few gaps near the west edge."}});
  if(await prisma.issue.count({where:{fieldId:field.id,status:IssueStatus.OPEN}})===0)await prisma.issue.create({data:{fieldId:field.id,sectorId:sectors[2].id,title:"Drip-line pressure concern",category:"Irrigation leak",severity:Priority.HIGH,status:IssueStatus.OPEN,description:"Sample issue: pressure appeared uneven near the south valve."}});
  if(await prisma.cropGuide.count({where:{cropId:crop.id}})===0){const guide=await prisma.cropGuide.create({data:{cropId:crop.id,title:"FarmPulse sample corn guide"}});await prisma.cropGuideArticle.createMany({data:[{guideId:guide.id,title:"Scout seedling emergence",summary:"Inspect gaps and uneven areas.",content:"Sample educational content. Walk a consistent scouting pattern and record gaps, insects, damage, and standing water.",stage:"Seedling",category:"Field scouting",sourceName:"Sample content — validate locally",lastReviewedAt:at(1),regionApplicability:"Tropical lowland corn"},{guideId:guide.id,title:"Irrigation during establishment",summary:"Maintain adequate seed-zone moisture without saturation.",content:"Sample educational content. Confirm root-zone moisture in the field before irrigating.",stage:"Seedling",category:"Irrigation",sourceName:"Sample content — validate locally",lastReviewedAt:at(1),regionApplicability:"Tropical lowland corn"}]});}
  if(await prisma.weatherSnapshot.count({where:{farmId:farm.id}})===0)await prisma.weatherSnapshot.create({data:{farmId:farm.id,observedAt:at(31,15,20),temperatureC:29,humidityPct:76,windKph:8,precipitationMm:0,rainProbability:20,payload:{sample:true}}});
  await prisma.appSetting.upsert({where:{farmId_key:{farmId:farm.id,key:"irrigation_design"}},update:{},create:{farmId:farm.id,key:"irrigation_design",value:{rows:133,rowLengthM:100,rowSpacingM:0.75,plantSpacingM:0.22,dripTapeMm:16,emitterSpacingM:0.30,sectorFlowM3h:11,targetPressureBar:[1,1.5],storageTankLiters:24000}}});
  console.log("FarmPulse seed complete",{admin:admin.email,operator:operator.email,farm:farm.name});
}
main().catch(e=>{console.error(e);process.exit(1)}).finally(()=>prisma.$disconnect());
