export const LAND_DESIGN_SETTING_KEY = "land_design_may_2024";

export const MAY_2024_LAND_DESIGN = {
  document: {
    title: "Finca Agrícola — Sistema de riego por goteo",
    drawing: "Plano de riego No. 03F — Ajustado",
    revision: "Diseño corregido final",
    date: "2024-05",
    scale: "1:1,000",
    evidenceStatus: "PLANNED_NOT_FIELD_VERIFIED",
    source: "Owner-provided reference drawing",
    cropLabelInterpretation: "Corn and Melon labels are illustrative examples on the drawing, not assigned crops.",
  },
  coordinateSystem: { datum: "WGS 84", zone: "17N", units: "m" },
  boundaryVertices: [
    { vertex: 1, east: 371168.52, north: 923594.97 },
    { vertex: 2, east: 371150.35, north: 923584.53 },
    { vertex: 3, east: 371173.31, north: 923568.55 },
    { vertex: 4, east: 371119.84, north: 923305.45 },
    { vertex: 5, east: 371076.26, north: 923177.78 },
    { vertex: 6, east: 371015.21, north: 923078.72 },
    { vertex: 7, east: 370846.96, north: 923015.70 },
    { vertex: 8, east: 370684.31, north: 922987.21 },
    { vertex: 9, east: 370553.21, north: 922999.73 },
    { vertex: 10, east: 370426.02, north: 923038.79 },
    { vertex: 11, east: 370333.11, north: 923131.35 },
    { vertex: 12, east: 370378.9, north: 923240.67 },
    { vertex: 13, east: 370317.39, north: 923437.34 },
    { vertex: 14, east: 370290.02, north: 923479.28 },
    { vertex: 15, east: 370652.48, north: 923638.1 },
  ],
  areasHa: {
    totalProperty: 10,
    declaredProduction: 8,
    mappedProductionLots: 4,
    expansion: 1.6,
    infrastructure: 0.4,
    unresolvedProductionArea: 4,
  },
  lots: [
    { number: 1, name: "Lot 1", drawingExampleCrop: "Corn", plannedCrop: null, areaHa: 1, beds: 100, bedLengthM: 100, valve: "Gate valve 1" },
    { number: 2, name: "Lot 2", drawingExampleCrop: "Corn", plannedCrop: null, areaHa: 1, beds: 100, bedLengthM: 100, valve: "Gate valve 2" },
    { number: 3, name: "Lot 3", drawingExampleCrop: "Melon", plannedCrop: null, areaHa: 1, beds: 100, bedLengthM: 100, valve: "Gate valve 3" },
    { number: 4, name: "Lot 4", drawingExampleCrop: "Melon", plannedCrop: null, areaHa: 1, beds: 100, bedLengthM: 100, valve: "Gate valve 4" },
  ],
  irrigation: {
    source: "Río Chico",
    sequence: [
      "River intake pumping station (first pump)",
      "Gravel filter",
      "24,000 L storage tank",
      "Irrigation pressure pump (second pump)",
      "Disk filter",
      "4 in PVC main pipe",
      "2 in buried PVC secondary pipe",
      "Four independent gate valves",
      "Surface lateral connections for drip tape",
    ],
    tankLiters: 24000,
    mainPipeInches: 4,
    secondaryPipeInches: 2,
    dripTapeMm: 16,
    tapesPerBed: 2,
    emitterSpacingM: 0.2,
    drawingEmittersPerBed: 5000,
    computedEmittersPerBed: 1000,
    installationStatus: "NOT_FIELD_VERIFIED",
  },
  infrastructure: [
    { name: "Warehouse", dimensionsM: [12, 10], status: "PLANNED_NOT_VERIFIED" },
    { name: "Workshop", dimensionsM: [8, 6], status: "PLANNED_NOT_VERIFIED" },
    { name: "Office", dimensionsM: [6, 5], status: "PLANNED_NOT_VERIFIED" },
    { name: "Main gate", status: "PLANNED_NOT_VERIFIED" },
  ],
  roads: [
    { name: "Perimeter road", widthM: 5, status: "PLANNED_NOT_VERIFIED" },
    { name: "Main road", widthM: 5, status: "EXISTING_ON_DRAWING_NOT_FIELD_VERIFIED" },
    { name: "Secondary road", widthM: 5, status: "PLANNED_NOT_VERIFIED" },
  ],
  discrepancies: [
    {
      id: "production-area",
      severity: "HIGH",
      title: "Production-area discrepancy",
      detail: "The area table declares 8.00 ha under production, while the four mapped 1.00 ha lots total 4.00 ha.",
      resolution: "Confirm the location and layout of the remaining 4.00 ha before adding more production lots.",
    },
    {
      id: "emitter-count",
      severity: "HIGH",
      title: "Emitter-count discrepancy",
      detail: "Two 100 m tapes with emitters every 0.20 m compute to 1,000 emitters per bed; the drawing states 5,000.",
      resolution: "Confirm the hydraulic design and emitter count with the irrigation designer before calculating demand.",
    },
  ],
  verificationChecklist: [
    "Survey property boundary and confirm all 15 UTM vertices",
    "Locate the unresolved 4.00 ha declared as production area",
    "Confirm each lot area and 100-bed layout",
    "Confirm drip-tape count and emitter arithmetic",
    "Verify Río Chico intake location and seasonal availability",
    "Measure pump flow and pressure under load",
    "Verify gravel and disk filter specifications",
    "Verify 24,000 L tank installation and condition",
    "Trace main and secondary pipe routes",
    "Test each lot's independent gate valve",
    "Verify roads, gate, warehouse, workshop, and office in the field",
  ],
} as const;

export type LandDesign = typeof MAY_2024_LAND_DESIGN;
